# Generated by Django 2.1.5 on 2019-02-04 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='act',
            fields=[
                ('act_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('caption', models.CharField(max_length=200)),
                ('upvotes', models.IntegerField(default=0)),
                ('img_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
