# Generated by Django 2.1.5 on 2019-02-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=42)),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='username',
            field=models.ForeignKey(default='johndoe', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
